module.exports = [
  {
    files: ["scripts/js/*.js"],
    languageOptions: {
      ecmaVersion: 2015,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        history: "readonly",
        location: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        XMLHttpRequest: "readonly",
        AbortController: "readonly",
        DOMParser: "readonly",
        Set: "readonly",
        hljs: "readonly",
        mermaid: "readonly",
        sessionStorage: "readonly",
        // Cross-module functions (defined in other script files)
        fvLog: "readonly",
        fvLogError: "readonly",
        escapeHtml: "readonly",
        escapeCssSelector: "readonly",
        showToast: "readonly",
        copyToClipboard: "readonly",
        createElement: "readonly",
        activateTab: "readonly",
        createLoadingTab: "readonly",
        getFileIcon: "readonly",
        navigateToAdjacentTab: "readonly",
        closeActiveTab: "readonly",
        attachBodyListeners: "readonly",
        switchTabGroup: "readonly",
        updateGroupCounts: "readonly",
        showGroupLoading: "readonly",
        showGitLoading: "readonly",
        removeWatchedRepository: "readonly",
        createGroupHeader: "readonly",
        pollGroupCount: "readonly",
        openGitWatch: "readonly",
        closeGitWatch: "readonly",
        updateGitModeUI: "readonly",
        initializeContent: "readonly",
        initializeDiffCollapse: "readonly",
        performSwap: "readonly",
        saveViewState: "readonly",
        restoreViewState: "readonly",
        pollReload: "readonly",
        startReloadPoll: "readonly",
        startLoadingPoll: "readonly",
        startTimestampPoll: "readonly",
        abortPoller: "readonly",
        stopPoller: "readonly",
        stopAllPollers: "readonly",
        markDiffContext: "readonly",
        getDiffHunks: "readonly",
        jumpToDiff: "readonly",
        showDiffCounter: "readonly",
        toggleDiffCollapse: "readonly",
        toggleMdView: "readonly",
        themes: "readonly",
        applyTheme: "readonly",
        buildThemeCSS: "readonly",
        renderThemeGrid: "readonly",
        renderShortcutsPane: "readonly",
        openSettings: "readonly",
        closeSettings: "readonly",
        switchSettingsSection: "readonly",
        openSearchModal: "readonly",
        closeSearchModal: "readonly",
        toggleSearchModal: "readonly",
        selectModalItem: "readonly",
        renderSearchModal: "readonly",
        getActiveFilePath: "readonly",
        highlightLineUntilDismiss: "readonly",
        // Constants from constants.js
        DIFF_CONTEXT_LINES: "readonly",
        POLL_LOADING_INTERVAL: "readonly",
        POLL_RELOAD_INTERVAL: "readonly",
        POLL_TIMESTAMP_INTERVAL: "readonly",
        SUPPRESS_RELOAD_AFTER_CLOSE_MS: "readonly",
        SUPPRESS_RELOAD_AFTER_OPEN_MS: "readonly",
        PAGE_LOAD_GUARD_MS: "readonly",
        LOADING_TOAST_DELAY_MS: "readonly",
        TOAST_DURATION_MS: "readonly",
        HLJS_CDN_BASE: "readonly",
        CODE_FILE_EXTENSIONS: "readonly",
        CODE_FILE_NAMES: "readonly"
      }
    },
    rules: {
      "eqeqeq": "error",
      "no-empty": "error",
      "no-shadow": "warn",
      "no-unused-vars": ["warn", { "args": "none", "vars": "local", "caughtErrors": "none" }],
      "id-length": ["warn", { "min": 2, "exceptions": ["i", "j", "e", "s", "x", "y"] }],
      "max-lines-per-function": ["warn", { "max": 40, "skipBlankLines": true, "skipComments": true }],
      "no-var": "off",
      "no-console": "off"
    }
  }
];
